### ISSUE TITLE
PDF is not allowed to be distributed 

### ISSUE THREAD

**Issue by nealeu** [xudafeng/Tomato#1]
Hi,

You are unfortunately distributing copyrighted material for free, which is illegal.

To avoid this material being forceably removed using https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/, there's a friendly way to do it.

Could you please do the following:
- If you are familiar with git filter-branch or interactive rebase, then you can remove the Pomodoro Technique Illustrated PDF, and ensure that it is no longer in the git history, and then force-push the cleaned master branch over this one.
Or, more simply.
- Check out your code
- Delete the .git subdirectory.  
- Do `git init`
- Commit the code to the new repository
- Push the repository to a new github repo (e.g. Tomato2).
- Delete this repository from Github so that no public access to the PDF exists.

I'm sure you've innocently not realised that you were infringing the author's copyright, but this does have to be removed.

Thanks,
Neale

**Comment by xudafeng** [comment]
@nealeu sorry about this, i will remove the PDF

**Comment by xudafeng** [comment]
it's ok now
